spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service: #criando propriedade customizada.
  greeting: "ohayo"
  default-value: "Mundo"    